### ISSUE TITLE
Marker don't rotate and crashes when the prop rotationAngle changes

### ISSUE THREAD

**Issue by inspirity** [imudin/vue2-leaflet-rotatedmarker#3]
Working with NUXT framework.

It worked before and suddenly i get the follow Error when the prop markerAngle changes 

> TypeError: e[r] is not a function
>     at VueComponent.n.(:3000/anonymous function).custom.setOptions.t.$watch.deep (http://192.168.10.139:3000/_nuxt/21.js:14428:1521)
>     at Watcher.run (commons.app.js:13819)
>     at flushSchedulerQueue (commons.app.js:13567)
>     at Array.<anonymous> (commons.app.js:12423)
>     at flushCallbacks (commons.app.js:12344)

the template:
```
<l-rotated-marker 
            v-if="navModus>0"
            :lat-lng="markerPosition"
            :icon="shipIcon"
            :rotationAngle="markerAngle">
</l-rotated-marker>
```

function markerAngle send a Number Value between 0-360
replacing markerAngle with a fix number like 45 the marker don't rotate.

BTW at the wame time my vue2-leaflet-tracksymbol template also stopped working o may be the bug is somewhere else... ??

Any Idea how to proceed?
Thank you for any support.

Oliver

**Comment by mudin** [comment]
@inspirity I guess you updated vue2-leaflet recently. My other plugin didnt work neither and I found [this report](https://github.com/KoRiGaN/Vue2Leaflet/issues/281) which helps me to fix it.
Could you check it? if it still doesnt work, I will check my code too

**Comment by inspirity** [comment]
Thank you very much, this must be the problem. Will let you know.

**Comment by inspirity** [comment]
once i moved **leaflet** in vue2-lealfet package.json and in the vue2-leaflet-rotatedmarker package.json file to peerDependencies everything worked again. Thank you very much.
Would be great to do those changes in the repo too for the future.

**Comment by mudin** [comment]
You're welcome! Yes there are some issue with importing leaflet, for now we are trying to make the plugins as smaller as possible. People should add leaflet separately
