### ISSUE TITLE
upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "11.10.1"

### ISSUE THREAD

**Issue by 0x8f701** [imudin/vue2-leaflet-rotatedmarker#5]

**Comment by mudin** [comment]
what versions of the library and Nodejs are you using?

**Comment by 0x8f701** [comment]
@mudin hello, thanks for your reply, my nodejs version is `v11.10.1` and the library version I just cloned the repo and tried to run the example.

**Comment by mudin** [comment]
@GopherJ thank you for your report too! I have just updated my node to `v11.14.0` , and still everything is working

**Comment by mudin** [comment]
are you using `npm`?

**Comment by mudin** [comment]
Please use `npm`. I am not familiar with `yarn`

**Comment by 0x8f701** [comment]
it's strange, I tried to use `npm` and the error disappear...

Thanks for your help! Now it's working well!
