### ISSUE TITLE
How can I use this in <script></script>?

### ISSUE THREAD

**Issue by thammarith** [imudin/vue2-leaflet-rotatedmarker#7]
There're some reasons that I have to create markers inside the `<script></script>` but I can't get this working. What should I do to be able to rotate markers without using the component?

```html
<template>
  <l-map ... ref="myMap"></l-map>
</template>
```

```javascript
<script>
export default {
  ...,
  mounted() {
    ...
    const map = this.$refs.myMap.mapObject;

    L.marker([13.76, 100.5], {
      rotationAngle: 45, // doesn't work, nothing happened
      icon: L.icon({
        iconUrl: '(icon URL)',
      })
    }).addTo(map);
  }
}
</script>
```

Thanks!

**Comment by mudin** [comment]
I guess you wanna use the plugin directly.
Could you add `https://cdn.jsdelivr.net/npm/leaflet-rotatedmarker@0.2.0/leaflet.rotatedMarker.js`?
check this [example](https://jsfiddle.net/mudin/uyLz1qf0/)

**Comment by thammarith** [comment]
Thank you, that works too.

I went with another way because I'm not familiar with including through Webpack nor wanting to include in the `index.html` directly.

I got it working with [_importing a module for its side effects only_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Import_a_module_for_its_side_effects_only).

```javascript
import 'vue2-leaflet-rotatedmarker'; // Use this instead of import ... from ...

export default {
  ...,
  mounted() {
    L.marker([13.76, 100.5], {
      rotationAngle: 45,
    }).addTo(map);
  },
};
```

**Comment by mudin** [comment]
@thammarith You're welcome! I didn't know you could use es6 import. Of course this is better way!
